## This file includes two functions: makeCacheMatrix and cacheSolve.
## makeCacheMatrix generates a special "cacheMatrix" so that the inverse can be stored in the cache
## cacheSolve takes as input a cacheMatrix. If the inverse is already stored in the cache, it'll return that.
##    Otherwise, it'll use solve() to get the inverse, and store the inverse in the cache

## makeCacheMatrix takes a matrix as input. It'll return a cacheMatrix, with stored functions allowing one to get/set the matrix,
##  and also to get/set the inverse in a cache

makeCacheMatrix <- function(x = matrix()) {
    #determine if x is square
    if(nrow(x) != ncol(x)) stop(error="it is only possible to find the inverse of a square matrix")
    
    #set initial values to null
    inv <- NULL
    
    #function to set
    set <- function(y) {
        x <<- y
        inv <<- NULL
    }
    
    #function to get (value of x)
    get <- function() x
    
    #function to set inverse
    setinv <- function(tempinv) inv <<- tempinv
    
    #function to get inverse
    getinv <- function() inv
    
    #return a list of functions
    list(set = set, get = get, setinv = setinv, getinv = getinv)
}


## cacheSolve takes as input a cacheMatrix (generated by the cacheMatrix function), and returns the inverse
##  If the inverse is stored in the cache already, then it'll return that inverse.
##  Otherwise, it'll calculate the inverse using solve(), store the inverse in the cache,
##  and also return the calculated inverse.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    
    #check if data is in cache
    inv <- x$getinv()
    if(!is.null(inv)) {
        message("getting cached data")
        return(inv)
    }
    
    #function hasn't returned, so inverse wasn't in cache, hence we should put it there
    data <- x$get()
    inv <- solve(data, ...)
    x$setinv(inv)
    
    #now return the inverse
    inv
}
